version: 1.0.0
server:
  port: 8888
spring:
  application:
    name: dragonfly-center #表示应用名称
eureka:
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
  client:
    registerWithEureka: false      #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false       #表示是否从Eureka Server获取注册信息, 为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:                     #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka多个地址可使用 , 分隔
      defaultZone: http://localhost:${server.port}/eureka/