version: 1.0.0
spring:
  application:
    name: dragonfly-security #表示应用名称
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/dragonfly?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
server:
  port: 8860
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/