version: 1.0.0
spring:
  application:
    name: dragonfly-ui #表示应用名称
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
server:
  port: 8850
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/